import Foundation

/// What the user pastes in, and what the server answers with.
///
/// RULINGS.md R8: the pasted block carries **no secrets at all** — server
/// address, this Mac's name, the tunnel port and a single-use pairing code
/// (32 hex, valid 30 days). No private key is generated by the server, printed
/// by it, or carried anywhere. This Mac makes its own key pair and the private
/// half never leaves it.
struct PairingRequest {
    var macName: String
    var tunnelPort: Int
    var serverHost: String
    var tunnelUser: String
    /// 32 hex characters, single use.
    var code: String
    /// R10: the sshd port the tunnel will dial (22 unless the block says else).
    var serverSSHPort: Int
    /// R10: optional ProxyCommand for networks that block the direct route.
    var proxyCommand: String
    /// Where to POST {code, pubkey, name}. Derived from the server address when
    /// the block does not name it.
    var enrollURL: URL
}

/// What the enrolment endpoint gives back.
///
/// Final contract (`bin/enroll-server`):
///
///     POST <enroll_url>   {"code": "<32 hex>", "pubkey": "ssh-ed25519 …", "name": "<mac name>"}
///     200 {"ok": true, "name": "mbp", "tunnel_port": 2201, "tunnel_user": "tunnel",
///          "server_host": "…", "server_pubkey": "ssh-ed25519 … using-mac-server"}
///     400 {"ok": false, "error": "enrollment_failed", "message": "…"}
///
/// The failure shape is deliberately one code for every cause: a caller that
/// could tell "no such code" from "already used" from "expired" would be an
/// oracle for guessing codes.
///
/// **`name` and `tunnel_port` in the answer are authoritative** — they are what
/// the server actually wrote into `permitlisten=` and into its registry, so
/// they win over anything typed or pasted here.
struct PairingResult {
    var macName: String
    var tunnelPort: Int
    var tunnelUser: String
    var serverHost: String
    var serverPublicKey: String
}

enum PairingError: LocalizedError {
    case missingFields([String])
    case badCode
    case badPort(Int)
    case badEnrollURL(String)
    case carriesPrivateKey

    var errorDescription: String? {
        switch self {
        case .missingFields(let fields):
            return Lf("err.pairingUnparsable", fields.joined(separator: ", "))
        case .badCode:
            return L("err.pairingBadCode")
        case .badPort:
            return Lf("err.pairingBadPort", Config.portMin, Config.portMax)
        case .badEnrollURL(let text):
            return Lf("err.pairingBadURL", text)
        case .carriesPrivateKey:
            return L("err.pairingCarriesKey")
        }
    }
}

/// Parses what `mac setup` prints.
///
/// Three shapes are accepted, because a user pasting from a terminal will hit
/// all three sooner or later:
///   1. shell assignments   (MAC_NAME='x' TUNNEL_PORT=2201 PAIR_CODE=… )
///   2. a JSON object       (`mac setup --json`)
///   3. base64 of either
enum Pairing {

    static func parse(_ raw: String, fallbackHost: String = "") throws -> PairingRequest {
        let text = decodeIfBase64(raw.trimmingCharacters(in: .whitespacesAndNewlines))

        // R8: a block that still carries a private key comes from a server that
        // has not been updated — and that key has just been through a terminal,
        // a scrollback buffer and probably a chat log. Refuse it and say why.
        if text.contains("PRIVATE KEY") || text.contains("TUNNEL_KEY_B64") {
            throw PairingError.carriesPrivateKey
        }

        var fields = parseShellAssignments(text)
        // JSON wins where it overlaps: it is the machine-generated form.
        for (key, value) in parseJSONFields(text) {
            fields[key] = value
        }

        var missing: [String] = []
        let name = fields["MAC_NAME"] ?? ""
        var host = fields["SERVER_HOST"] ?? ""
        if host.isEmpty { host = fallbackHost }
        let portText = fields["TUNNEL_PORT"] ?? ""
        let user = fields["TUNNEL_USER"] ?? Config.defaultTunnelUser
        // `mac setup` prints PAIRING_CODE=; older docs said PAIR_CODE=. Both are
        // the same thing and both must work — this mismatch cost one real
        // afternoon.
        let code = normaliseCode(fields["PAIRING_CODE"] ?? fields["PAIR_CODE"] ?? "")

        if name.isEmpty { missing.append("MAC_NAME") }
        if host.isEmpty { missing.append("SERVER_HOST") }
        if portText.isEmpty { missing.append("TUNNEL_PORT") }
        if code.isEmpty { missing.append("PAIR_CODE") }
        if !missing.isEmpty { throw PairingError.missingFields(missing) }

        guard isValidCode(code) else { throw PairingError.badCode }
        guard let port = Int(portText),
              port >= Config.portMin, port <= Config.portMax else {
            throw PairingError.badPort(Int(portText) ?? 0)
        }

        var sshPort = Config.defaultServerSSHPort
        if let text = fields["SERVER_PORT"], let value = Int(text), value > 0, value <= 65535 {
            sshPort = value
        }
        let proxy = (fields["PROXY_COMMAND"] ?? "")
            .replacingOccurrences(of: "\n", with: " ")
            .trimmingCharacters(in: .whitespaces)

        let url = try enrollURL(from: fields["ENROLL_URL"], host: host)

        return PairingRequest(macName: name,
                              tunnelPort: port,
                              serverHost: host,
                              tunnelUser: user.isEmpty ? Config.defaultTunnelUser : user,
                              code: code,
                              serverSSHPort: sshPort,
                              proxyCommand: proxy,
                              enrollURL: url)
    }

    /// What one pasted thing is: a whole block, a bare code, or neither.
    ///
    /// The setup window has a single input on purpose (one box, one button), so
    /// it has to tell these apart itself instead of asking the user which kind
    /// of thing they pasted.
    enum Recognised {
        case block(PairingRequest)
        case code(String)
        case nothing
        case invalid(Error)
    }

    static func recognise(_ raw: String, fallbackHost: String) -> Recognised {
        let text = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        if text.isEmpty { return .nothing }
        // A bare code: 32 hex, possibly grouped with spaces or dashes.
        let bare = normaliseCode(text)
        if isValidCode(bare) && text.count <= 48
            && text.allSatisfy({ $0.isHexDigit || $0 == " " || $0 == "-" }) {
            return .code(bare)
        }
        do {
            return .block(try parse(text, fallbackHost: fallbackHost))
        } catch {
            return .invalid(error)
        }
    }

    /// The endpoint the block names, or the default one on the same server.
    static func enrollURL(from text: String?, host: String) throws -> URL {
        if let text = text, !text.isEmpty {
            guard let url = URL(string: text),
                  let scheme = url.scheme?.lowercased(),
                  scheme == "http" || scheme == "https",
                  url.host != nil else {
                throw PairingError.badEnrollURL(text)
            }
            return url
        }
        let literal = host.contains(":") && !host.hasPrefix("[") ? "[\(host)]" : host   // IPv6
        guard let url = URL(string: "http://\(literal):\(Config.defaultEnrollPort)/enroll") else {
            throw PairingError.badEnrollURL(host)
        }
        return url
    }

    /// 32 hex characters, case-insensitive, with any grouping the user's
    /// terminal may have introduced removed.
    static func normaliseCode(_ raw: String) -> String {
        return raw.lowercased().filter { $0.isHexDigit }
    }

    static func isValidCode(_ code: String) -> Bool {
        return code.count == 32 && code.allSatisfy { $0.isHexDigit }
    }

    // MARK: - shapes

    private static func decodeIfBase64(_ text: String) -> String {
        // Only when the whole paste is one base64 blob; a shell block contains
        // spaces and quotes, so it never reaches here by accident.
        let compact = text.filter { !$0.isWhitespace }
        guard compact.count > 64,
              compact.allSatisfy({ "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".contains($0) }),
              let data = Data(base64Encoded: compact, options: [.ignoreUnknownCharacters]),
              let decoded = String(data: data, encoding: .utf8) else {
            return text
        }
        return decoded
    }

    private static let knownKeys = [
        "MAC_NAME", "TUNNEL_PORT", "SERVER_HOST", "TUNNEL_USER",
        "PAIRING_CODE", "PAIR_CODE", "ENROLL_URL", "SERVER_PORT", "PROXY_COMMAND"
    ]

    /// Finds `KEY=value` assignments anywhere in the text, with shell quoting
    /// handled the way `lib/remote.sh`'s `shq` produces it (`'…'\''…'`).
    private static func parseShellAssignments(_ text: String) -> [String: String] {
        let chars = Array(text)
        var out: [String: String] = [:]
        var index = 0

        while index < chars.count {
            // an assignment can only start at the beginning or after whitespace
            let atBoundary = (index == 0) || chars[index - 1].isWhitespace
                || chars[index - 1] == "\\"
            if atBoundary {
                for key in knownKeys where out[key] == nil {
                    if matches(chars, at: index, key + "=") {
                        var cursor = index + key.count + 1
                        let value = readShellWord(chars, &cursor)
                        if !value.isEmpty {
                            out[key] = value
                        }
                        index = cursor
                        break
                    }
                }
            }
            index += 1
        }
        return out
    }

    private static func matches(_ chars: [Character], at index: Int, _ needle: String) -> Bool {
        let needleChars = Array(needle)
        if index + needleChars.count > chars.count { return false }
        for offset in 0..<needleChars.count where chars[index + offset] != needleChars[offset] {
            return false
        }
        return true
    }

    /// Reads one shell word, resolving single quotes, double quotes and
    /// backslash escapes. Stops at the first *unquoted* whitespace.
    private static func readShellWord(_ chars: [Character], _ index: inout Int) -> String {
        var out = ""
        while index < chars.count {
            let ch = chars[index]
            if ch == "'" {
                index += 1
                while index < chars.count && chars[index] != "'" {
                    out.append(chars[index])
                    index += 1
                }
                if index < chars.count { index += 1 }   // closing quote
            } else if ch == "\"" {
                index += 1
                while index < chars.count && chars[index] != "\"" {
                    if chars[index] == "\\" && index + 1 < chars.count {
                        index += 1
                    }
                    out.append(chars[index])
                    index += 1
                }
                if index < chars.count { index += 1 }
            } else if ch == "\\" {
                // A line continuation ends the word; any other escape is literal.
                if index + 1 < chars.count && chars[index + 1] == "\n" { break }
                if index + 1 < chars.count {
                    index += 1
                    out.append(chars[index])
                    index += 1
                } else {
                    break
                }
            } else if ch.isWhitespace {
                break
            } else {
                out.append(ch)
                index += 1
            }
        }
        return out
    }

    /// Accepts both the snake_case emitted by `mac setup --json` and the
    /// SHOUTING_CASE of the shell block.
    private static func parseJSONFields(_ text: String) -> [String: String] {
        guard let start = text.firstIndex(of: "{"),
              let end = text.lastIndex(of: "}"),
              start < end else { return [:] }
        let slice = String(text[start...end])
        guard let data = slice.data(using: .utf8),
              let object = try? JSONSerialization.jsonObject(with: data),
              let dict = object as? [String: Any] else { return [:] }

        let aliases: [String: [String]] = [
            "MAC_NAME":      ["MAC_NAME", "macName", "host", "name"],
            "TUNNEL_PORT":   ["TUNNEL_PORT", "tunnelPort", "tunnel_port", "port"],
            "SERVER_HOST":   ["SERVER_HOST", "serverHost", "server", "server_host"],
            "TUNNEL_USER":   ["TUNNEL_USER", "tunnelUser", "tunnel_user"],
            "PAIR_CODE":     ["PAIRING_CODE", "PAIR_CODE", "pairing_code", "pair_code", "pairCode", "code"],
            "ENROLL_URL":    ["ENROLL_URL", "enroll_url", "enrollURL", "enroll_endpoint"],
            "SERVER_PORT":   ["SERVER_PORT", "server_port", "serverPort", "ssh_port"],
            "PROXY_COMMAND": ["PROXY_COMMAND", "proxy_command", "proxyCommand", "proxy"]
        ]

        var out: [String: String] = [:]
        for (canonical, names) in aliases {
            for name in names {
                guard let value = dict[name] else { continue }
                if let s = value as? String, !s.isEmpty {
                    out[canonical] = s
                } else if let n = value as? Int {
                    out[canonical] = String(n)
                } else {
                    continue
                }
                break
            }
        }
        return out
    }
}
